#!/bin/sh

set -e

# This is to ensure all I/O commands are synchronized before next command
sync

echo copying $DIRECTORY_NAME_TO_COPY from $SOURCE_ROOT_DIRECTORY to $TARGET_ROOT_DIRECTORY and the file to copy is $FILE_TO_COPY exluded files $EXCLUDE_FOLDERS_TO_COPY

cd $WORKSPACE

# Finding the file or directory to copy from source
SOURCE=$(find $SOURCE_ROOT_DIRECTORY -type $SOURCE_FILE_TYPE -name $SOURCE_ROOT_FILE)

echo this is the source file and $SOURCE

# Finding the file or directory to copy from source to destination
TARGET=$(find $TARGET_ROOT_DIRECTORY -maxdepth $MAX_DEPTH -type $DESTINATION_FILE_TYPE $EXCLUDE_FOLDERS_TO_COPY)

echo this is the destination file $TARGET

echo Copying $SOURCE to $TARGET

cp -r $SOURCE $TARGET

# This is to ensure all I/O commands are synchronized before next command
sync
