#!/bin/sh

# in this we will run karma test cases
set -e

echo executing Angular unit tests using karma in $WORKSPACE

cd $WORKSPACE

# Karma test cases goes to this folder, hence clean it up before running the tests
rm -rf $REPORT_OUTPUT_DIR

echo running with NPM_OPTIONS as $NPM_OPTIONS
echo "-----------------------------------"
echo overriding karm config file $OVERRIDE_KARMA_CONFIG_FILE with $EXTENDED_KARMA_CONFIG_FILE
echo passing NPM_SCRIPT_OPTIONS as $NPM_SCRIPT_OPTIONS

# Finding the target file to run the karma test cases
TARGET_FOLDER_TO_BUILD=$(find -maxdepth $MAX_DEPTH -type d $EXCLUDE_FOLDERS_TO_RUN)

echo Directory to run karma tests $TARGET_FOLDER_TO_BUILD

cd $TARGET_FOLDER_TO_BUILD

echo "this is the file " $TARGET_FOLDER_TO_BUILD

# Pass the config explicilty so that that config is used instead of the default
npm run test $NPM_OPTIONS -- --config $EXTENDED_KARMA_CONFIG_FILE $NPM_SCRIPT_OPTIONS
