#!/bin/sh

# in this we will run karma test cases
set -e

echo executing Angular unit tests using karma in $WORKSPACE

cd $WORKSPACE

# Karma test cases goes to this folder, hence clean it up before running the tests
rm -rf $REPORT_OUTPUT_DIR

echo running with NPM_OPTIONS as $NPM_OPTIONS
echo "-----------------------------------"
echo overriding karm config file $OVERRIDE_KARMA_CONFIG_FILE with $EXTENDED_KARMA_CONFIG_FILE
echo passing NPM_SCRIPT_OPTIONS as $NPM_SCRIPT_OPTIONS

# Pass the config explicilty so that that config is used instead of the default
npm run test $NPM_OPTIONS -- --config $EXTENDED_KARMA_CONFIG_FILE $NPM_SCRIPT_OPTIONS
