version: '2'
services:
  swunix:
    image: serviceworkers-unix:1.0.0
    build: ./unix
    network_mode: host
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-south-1"
        awslogs-group: "Hobbes-Container-Logs"
        awslogs-stream: "Hobbes-Base-LP-Prod-serviceworkers"
    restart: always
    volumes:
      - /nfsdata:/workspaces
    env_file: "docker-${NODE_ENV}.env"
