#javascript assignment
version: '1'
stages:
  git-clone-baserepo:
    type: stackroute/git/clone
    input:
      REPOSITORY_URL: "{{payload.baseRepoUrl}}"
      BRANCH: master
      WORKSPACE: "{{context.WORKSPACE}}/baseRepo"
  git-clone-submission:
    type: stackroute/git/clone
    input:
      REPOSITORY_URL: "{{payload.submissionRepoUrl}}"
      BRANCH: master
      WORKSPACE: "{{context.WORKSPACE}}/submission"
  git-clone-solution:
    type: stackroute/git/clone
    input:
      REPOSITORY_URL: "{{payload.solutionRepoUrl}}"
      BRANCH: master
      WORKSPACE: "{{context.WORKSPACE}}/solution"
  git-clone-asttest:
    type: stackroute/git/clone
    input:
      REPOSITORY_URL: "ssh://git@gitlab-dev.stackroute.in:2222/hobbes/ast-analysis.git"
      BRANCH: dev
      WORKSPACE: "{{context.WORKSPACE}}/tools"
    depends_on:
      - git-clone-submission
  build-asttest:
    type: stackroute/javascript/build
    input:
      WORKSPACE: "{{context.WORKSPACE}}/tools"
    output:
      payload:
        output:
          buildAstTest:
            status: \{\{EXITCODE\}\}
            output: \{\{OUTPUT\}\}
            errors: \{\{ERRORS\}\}
            summary: \{\{SUMMARY\}\}
    depends_on:
      - git-clone-asttest
  copy-baserepo-eslint:
    type: stackroute/unix/copy
    input:
      SOURCE: "baseRepo/.eslintrc.js"
      DESTINATION: "submission"
    depends_on:
      - git-clone-baserepo
      - git-clone-submission
  copy-baserepo-smellsrc:
    type: stackroute/unix/copy
    input:
      SOURCE: "baseRepo/.smellsrc.js"
      DESTINATION: "submission"
    depends_on:
      - git-clone-baserepo
      - git-clone-submission
  copy-baserepo-htmlhint:
    type: stackroute/unix/copy
    input:
      SOURCE: "baseRepo/.htmlhintrc"
      DESTINATION: "submission"
    depends_on:
      - git-clone-baserepo
      - git-clone-submission
  safecopy-smellsrc-to-submission:
    type: stackroute/unix/safecopy
    input:
      SOURCE: "solution/.smellsrc"
      DESTINATION: "submission"
    depends_on:
      - git-clone-baserepo
      - git-clone-solution
      - git-clone-submission
  safecopy-htmlhint-to-submission:
    type: stackroute/unix/safecopy
    input:
      SOURCE: "solution/.htmlhintrc"
      DESTINATION: "submission"
    depends_on:
      - git-clone-baserepo
      - git-clone-solution
      - git-clone-submission
  safecopy-eslint-to-submission:
    type: stackroute/unix/safecopy
    input:
      SOURCE: "solution/.eslintrc.js"
      DESTINATION: "submission"
    depends_on:
      - git-clone-baserepo
      - git-clone-solution
      - git-clone-submission
  safecopy-commandertests-to-submission:
    type: stackroute/unix/safecopy
    input:
      SOURCE: "solution/test"
      DESTINATION: "submission/commander"
    depends_on:
      - git-clone-baserepo
      - git-clone-submission
      - git-clone-solution
  copy-UI-Test:
    type: stackroute/unix/copy
    input:
      SOURCE: "solution/UI-Test"
      DESTINATION: "submission/UI-Commander"
    depends_on:
      - git-clone-solution
      - git-clone-submission
  run-smellsrc:
    type: stackroute/javascript/eslint
    input:
      RULES_FILE: ".smellsrc"
      WORKSPACE: "{{context.WORKSPACE}}/submission"
      IGNORE_PATTERN: --ignore-pattern html/**/*.js --ignore-pattern data/**/*.js --ignore-pattern UI-Commander/**/*.js --ignore-pattern commander/**/*.js --ignore-pattern UI-Test/**/*.js
    output:
      payload:
        output:
          lint:
            smells:
              status: \{\{EXITCODE\}\}
              output: \{\{OUTPUT\}\}
              errors: \{\{ERRORS\}\}
              summary: \{\{SUMMARY\}\}
    depends_on:
      - copy-baserepo-smellsrc
      - safecopy-smellsrc-to-submission
  run-eslintrc:
    type: stackroute/javascript/eslint
    input:
      RULES_FILE: ".eslintrc"
      WORKSPACE: "{{context.WORKSPACE}}/submission"
      IGNORE_PATTERN: --ignore-pattern html/**/*.js --ignore-pattern data/**/*.js --ignore-pattern UI-Commander/**/*.js --ignore-pattern commander/**/*.js --ignore-pattern UI-Test/**/*.js
    output:
      payload:
        output:
          lint:
            eslint:
              status: \{\{EXITCODE\}\}
              output: \{\{OUTPUT\}\}
              errors: \{\{ERRORS\}\}
              summary: \{\{SUMMARY\}\}
    depends_on:
      - copy-baserepo-eslint
      - safecopy-eslint-to-submission
  run-htmlhintrc:
    type: stackroute/javascript/htmlhint
    input:
      RULES_FILE: ".htmlhintrc"
      WORKSPACE: "{{context.WORKSPACE}}/submission"
      IGNORE_FILES: "**/data/**,**/UI-Commander/**,**/commander/**" #Make sure there are no spaces in the ignore file list
    output:
      payload:
        output:
          lint:
            htmlhint:
              status: \{\{EXITCODE\}\}
              output: \{\{OUTPUT\}\}
              errors: \{\{ERRORS\}\}
              summary: \{\{SUMMARY\}\}
    depends_on:
      - copy-baserepo-htmlhint
      - safecopy-htmlhint-to-submission
  delete-data-directory:
    type: stackroute/unix/delete
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
      FILES: data
    depends_on:
      - git-clone-submission
  delete-output-directory:
    type: stackroute/unix/delete
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
      FILES: output
    depends_on:
      - git-clone-submission
  create-output-directory:
    type: stackroute/unix/mkdir
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
      FILES: output
    depends_on:
      - delete-output-directory
  link-data-directory:
    type: stackroute/unix/link
    input:
      SOURCE: /data
      DESTINATION: "{{context.WORKSPACE}}/submission"
    depends_on:
      - delete-data-directory
  build-project:
    type: stackroute/javascript/build
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
    output:
      payload:
        output:
          build:
            status: \{\{EXITCODE\}\}
            output: \{\{OUTPUT\}\}
            errors: \{\{ERRORS\}\}
            summary: \{\{SUMMARY\}\}
    depends_on:
      - git-clone-submission
      - delete-data-directory
      - delete-output-directory
      - delete-data-directory
  run-project:
    type: stackroute/javascript/start
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
    output:
      payload:
        output:
          run:
            status: \{\{EXITCODE\}\}
            output: \{\{OUTPUT\}\}
            errors: \{\{ERRORS\}\}
            summary: \{\{SUMMARY\}\}
    depends_on:
      - build-project
      - link-data-directory
  run-commander-tests:
    type: stackroute/javascript/mocha
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
    output:
      payload:
        output:
          tests:
            commanderTests:
              status: \{\{EXITCODE\}\}
              output: \{\{OUTPUT\}\}
              errors: \{\{ERRORS\}\}
              summary: \{\{SUMMARY\}\}
    depends_on:
      - build-project
      - run-project
      - build-asttest
  run-cadet-tests:
    type: stackroute/javascript/mocha
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
    output:
      payload:
        output:
          tests:
            cadetTests:
              status: \{\{EXITCODE\}\}
              output: \{\{OUTPUT\}\}
              errors: \{\{ERRORS\}\}
              summary: \{\{SUMMARY\}\}
    depends_on:
      - run-project
      - build-project
      - build-asttest
  run-commander-phantom-tests:
    type: stackroute/phantomjs/phantom
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
      EXEC_FILE: "UI-Commander/index.html"
    output:
      payload:
        output:
          tests:
            commanderPhantomTests:
              status: \{\{EXITCODE\}\}
              output: \{\{OUTPUT\}\}
              errors: \{\{ERRORS\}\}
              summary: \{\{SUMMARY\}\}
    depends_on:
      - copy-UI-Commander
      - run-project
  run-cadet-phantom-tests:
    type: stackroute/phantomjs/phantom
    input:
      WORKSPACE: "{{context.WORKSPACE}}/submission"
      EXEC_FILE: "UI-Test/index.html"
    output:
      payload:
        output:
          tests:
            cadetPhantomTests:
              status: \{\{EXITCODE\}\}
              output: \{\{OUTPUT\}\}
              errors: \{\{ERRORS\}\}
              summary: \{\{SUMMARY\}\}
    depends_on:
      - copy-UI-Test
      - run-project
